CREATE OR REPLACE PROCEDURE P_ASP_INSERT_USERSTATUS
(
    v_resultcode        OUT NUMBER,
    v_resulterrinfo     OUT VARCHAR2
)
-----------------------------------------------------
--VerisBilling参数割接使用
-----------------------------------------------------
AS
BEGIN
    v_resultcode := 0;
    v_resulterrinfo := 'P_ASP_INSERT_USERSTATUS 过程执行成功!';

    BEGIN
    
delete from SD.SYS_USER_STATUS_AFFECT_DEF;
delete from SD.SYS_USER_STATUS_DTL;
COMMIT;

insert into SD.SYS_USER_STATUS_DTL(USER_STATUS_DEF,STS,OS_STS,FRAULD_FLAG,USERREQUEST_FLAG,UNBILLING_FLAG,OS_STS_DTL) values ('1000','1','10','-1','-1','-1','0');
insert into SD.SYS_USER_STATUS_DTL(USER_STATUS_DEF,STS,OS_STS,FRAULD_FLAG,USERREQUEST_FLAG,UNBILLING_FLAG,OS_STS_DTL) values ('1001','1','12','-1','-1','-1','1');
insert into SD.SYS_USER_STATUS_DTL(USER_STATUS_DEF,STS,OS_STS,FRAULD_FLAG,USERREQUEST_FLAG,UNBILLING_FLAG,OS_STS_DTL) values ('1002','1','12','-1','-1','-1','2');
insert into SD.SYS_USER_STATUS_DTL(USER_STATUS_DEF,STS,OS_STS,FRAULD_FLAG,USERREQUEST_FLAG,UNBILLING_FLAG,OS_STS_DTL) values ('1003','1','12','-1','-1','-1','3');
insert into SD.SYS_USER_STATUS_DTL(USER_STATUS_DEF,STS,OS_STS,FRAULD_FLAG,USERREQUEST_FLAG,UNBILLING_FLAG,OS_STS_DTL) values ('1004','1','12','-1','-1','-1','4');
insert into SD.SYS_USER_STATUS_DTL(USER_STATUS_DEF,STS,OS_STS,FRAULD_FLAG,USERREQUEST_FLAG,UNBILLING_FLAG,OS_STS_DTL) values ('1005','1','12','-1','-1','-1','5');
insert into SD.SYS_USER_STATUS_DTL(USER_STATUS_DEF,STS,OS_STS,FRAULD_FLAG,USERREQUEST_FLAG,UNBILLING_FLAG,OS_STS_DTL) values ('1006','22','12','-1','-1','-1','6');
insert into SD.SYS_USER_STATUS_DTL(USER_STATUS_DEF,STS,OS_STS,FRAULD_FLAG,USERREQUEST_FLAG,UNBILLING_FLAG,OS_STS_DTL) values ('1007','1','12','-1','-1','-1','7');
insert into SD.SYS_USER_STATUS_DTL(USER_STATUS_DEF,STS,OS_STS,FRAULD_FLAG,USERREQUEST_FLAG,UNBILLING_FLAG,OS_STS_DTL) values ('1008','23','12','-1','-1','-1','8');
insert into SD.SYS_USER_STATUS_DTL(USER_STATUS_DEF,STS,OS_STS,FRAULD_FLAG,USERREQUEST_FLAG,UNBILLING_FLAG,OS_STS_DTL) values ('1009','24','12','-1','-1','-1','9');
insert into SD.SYS_USER_STATUS_DTL(USER_STATUS_DEF,STS,OS_STS,FRAULD_FLAG,USERREQUEST_FLAG,UNBILLING_FLAG,OS_STS_DTL) values ('1010','1','11','-1','-1','-1','5');
insert into SD.SYS_USER_STATUS_DTL(USER_STATUS_DEF,STS,OS_STS,FRAULD_FLAG,USERREQUEST_FLAG,UNBILLING_FLAG,OS_STS_DTL) values ('1011','1','11','-1','-1','-1','7');
insert into SD.SYS_USER_STATUS_DTL(USER_STATUS_DEF,STS,OS_STS,FRAULD_FLAG,USERREQUEST_FLAG,UNBILLING_FLAG,OS_STS_DTL) values ('1012','1','12','-1','-1','-1','5');
insert into SD.SYS_USER_STATUS_DTL(USER_STATUS_DEF,STS,OS_STS,FRAULD_FLAG,USERREQUEST_FLAG,UNBILLING_FLAG,OS_STS_DTL) values ('1013','1','12','-1','-1','-1','7');
insert into SD.SYS_USER_STATUS_DTL(USER_STATUS_DEF,STS,OS_STS,FRAULD_FLAG,USERREQUEST_FLAG,UNBILLING_FLAG,OS_STS_DTL) values ('1014','1','12','-1','-1','-1','10');
insert into SD.SYS_USER_STATUS_DTL(USER_STATUS_DEF,STS,OS_STS,FRAULD_FLAG,USERREQUEST_FLAG,UNBILLING_FLAG,OS_STS_DTL) values ('1015','21','12','-1','-1','-1','11');
insert into SD.SYS_USER_STATUS_DTL(USER_STATUS_DEF,STS,OS_STS,FRAULD_FLAG,USERREQUEST_FLAG,UNBILLING_FLAG,OS_STS_DTL) values ('1016','1','12','-1','-1','-1','8');
insert into SD.SYS_USER_STATUS_DTL(USER_STATUS_DEF,STS,OS_STS,FRAULD_FLAG,USERREQUEST_FLAG,UNBILLING_FLAG,OS_STS_DTL) values ('1017','1','12','-1','-1','-1','40');
insert into SD.SYS_USER_STATUS_DTL(USER_STATUS_DEF,STS,OS_STS,FRAULD_FLAG,USERREQUEST_FLAG,UNBILLING_FLAG,OS_STS_DTL) values ('1018','1','12','-1','-1','-1','40');
insert into SD.SYS_USER_STATUS_DTL(USER_STATUS_DEF,STS,OS_STS,FRAULD_FLAG,USERREQUEST_FLAG,UNBILLING_FLAG,OS_STS_DTL) values ('1019','1','12','-1','-1','-1','20');
insert into SD.SYS_USER_STATUS_DTL(USER_STATUS_DEF,STS,OS_STS,FRAULD_FLAG,USERREQUEST_FLAG,UNBILLING_FLAG,OS_STS_DTL) values ('1020','1','12','-1','-1','-1','41');
insert into SD.SYS_USER_STATUS_DTL(USER_STATUS_DEF,STS,OS_STS,FRAULD_FLAG,USERREQUEST_FLAG,UNBILLING_FLAG,OS_STS_DTL) values ('1021','25','12','-1','-1','-1','6');
insert into SD.SYS_USER_STATUS_DTL(USER_STATUS_DEF,STS,OS_STS,FRAULD_FLAG,USERREQUEST_FLAG,UNBILLING_FLAG,OS_STS_DTL) values ('1022','26','12','-1','-1','-1','6');
insert into SD.SYS_USER_STATUS_DTL(USER_STATUS_DEF,STS,OS_STS,FRAULD_FLAG,USERREQUEST_FLAG,UNBILLING_FLAG,OS_STS_DTL) values ('1023','0','10','-1','-1','-1','0');
insert into SD.SYS_USER_STATUS_DTL(USER_STATUS_DEF,STS,OS_STS,FRAULD_FLAG,USERREQUEST_FLAG,UNBILLING_FLAG,OS_STS_DTL) values ('1024','0','12','-1','-1','-1','1');
insert into SD.SYS_USER_STATUS_DTL(USER_STATUS_DEF,STS,OS_STS,FRAULD_FLAG,USERREQUEST_FLAG,UNBILLING_FLAG,OS_STS_DTL) values ('1025','0','12','-1','-1','-1','2');
insert into SD.SYS_USER_STATUS_DTL(USER_STATUS_DEF,STS,OS_STS,FRAULD_FLAG,USERREQUEST_FLAG,UNBILLING_FLAG,OS_STS_DTL) values ('1026','0','12','-1','-1','-1','3');
insert into SD.SYS_USER_STATUS_DTL(USER_STATUS_DEF,STS,OS_STS,FRAULD_FLAG,USERREQUEST_FLAG,UNBILLING_FLAG,OS_STS_DTL) values ('1027','0','12','-1','-1','-1','4');
insert into SD.SYS_USER_STATUS_DTL(USER_STATUS_DEF,STS,OS_STS,FRAULD_FLAG,USERREQUEST_FLAG,UNBILLING_FLAG,OS_STS_DTL) values ('1028','0','12','-1','-1','-1','5');
insert into SD.SYS_USER_STATUS_DTL(USER_STATUS_DEF,STS,OS_STS,FRAULD_FLAG,USERREQUEST_FLAG,UNBILLING_FLAG,OS_STS_DTL) values ('1029','0','12','-1','-1','-1','7');
insert into SD.SYS_USER_STATUS_DTL(USER_STATUS_DEF,STS,OS_STS,FRAULD_FLAG,USERREQUEST_FLAG,UNBILLING_FLAG,OS_STS_DTL) values ('1030','0','11','-1','-1','-1','5');
insert into SD.SYS_USER_STATUS_DTL(USER_STATUS_DEF,STS,OS_STS,FRAULD_FLAG,USERREQUEST_FLAG,UNBILLING_FLAG,OS_STS_DTL) values ('1031','0','11','-1','-1','-1','7');
insert into SD.SYS_USER_STATUS_DTL(USER_STATUS_DEF,STS,OS_STS,FRAULD_FLAG,USERREQUEST_FLAG,UNBILLING_FLAG,OS_STS_DTL) values ('1032','0','12','-1','-1','-1','5');
insert into SD.SYS_USER_STATUS_DTL(USER_STATUS_DEF,STS,OS_STS,FRAULD_FLAG,USERREQUEST_FLAG,UNBILLING_FLAG,OS_STS_DTL) values ('1033','0','12','-1','-1','-1','7');
insert into SD.SYS_USER_STATUS_DTL(USER_STATUS_DEF,STS,OS_STS,FRAULD_FLAG,USERREQUEST_FLAG,UNBILLING_FLAG,OS_STS_DTL) values ('1034','0','12','-1','-1','-1','10');
insert into SD.SYS_USER_STATUS_DTL(USER_STATUS_DEF,STS,OS_STS,FRAULD_FLAG,USERREQUEST_FLAG,UNBILLING_FLAG,OS_STS_DTL) values ('1035','0','12','-1','-1','-1','11');
insert into SD.SYS_USER_STATUS_DTL(USER_STATUS_DEF,STS,OS_STS,FRAULD_FLAG,USERREQUEST_FLAG,UNBILLING_FLAG,OS_STS_DTL) values ('1036','0','12','-1','-1','-1','8');
insert into SD.SYS_USER_STATUS_DTL(USER_STATUS_DEF,STS,OS_STS,FRAULD_FLAG,USERREQUEST_FLAG,UNBILLING_FLAG,OS_STS_DTL) values ('1037','0','12','-1','-1','-1','40');
insert into SD.SYS_USER_STATUS_DTL(USER_STATUS_DEF,STS,OS_STS,FRAULD_FLAG,USERREQUEST_FLAG,UNBILLING_FLAG,OS_STS_DTL) values ('1038','0','12','-1','-1','-1','40');
insert into SD.SYS_USER_STATUS_DTL(USER_STATUS_DEF,STS,OS_STS,FRAULD_FLAG,USERREQUEST_FLAG,UNBILLING_FLAG,OS_STS_DTL) values ('1039','0','12','-1','-1','-1','20');
insert into SD.SYS_USER_STATUS_DTL(USER_STATUS_DEF,STS,OS_STS,FRAULD_FLAG,USERREQUEST_FLAG,UNBILLING_FLAG,OS_STS_DTL) values ('1040','0','12','-1','-1','-1','41');
insert into SD.SYS_USER_STATUS_DTL(USER_STATUS_DEF,STS,OS_STS,FRAULD_FLAG,USERREQUEST_FLAG,UNBILLING_FLAG,OS_STS_DTL) values ('1041','0','10','-1','-1','-1','0');
insert into SD.SYS_USER_STATUS_DTL(USER_STATUS_DEF,STS,OS_STS,FRAULD_FLAG,USERREQUEST_FLAG,UNBILLING_FLAG,OS_STS_DTL) values ('1042','0','12','-1','-1','-1','1');
insert into SD.SYS_USER_STATUS_DTL(USER_STATUS_DEF,STS,OS_STS,FRAULD_FLAG,USERREQUEST_FLAG,UNBILLING_FLAG,OS_STS_DTL) values ('1043','0','12','-1','-1','-1','2');
insert into SD.SYS_USER_STATUS_DTL(USER_STATUS_DEF,STS,OS_STS,FRAULD_FLAG,USERREQUEST_FLAG,UNBILLING_FLAG,OS_STS_DTL) values ('1044','0','12','-1','-1','-1','3');
insert into SD.SYS_USER_STATUS_DTL(USER_STATUS_DEF,STS,OS_STS,FRAULD_FLAG,USERREQUEST_FLAG,UNBILLING_FLAG,OS_STS_DTL) values ('1045','0','12','-1','-1','-1','4');
insert into SD.SYS_USER_STATUS_DTL(USER_STATUS_DEF,STS,OS_STS,FRAULD_FLAG,USERREQUEST_FLAG,UNBILLING_FLAG,OS_STS_DTL) values ('1046','0','12','-1','-1','-1','5');
insert into SD.SYS_USER_STATUS_DTL(USER_STATUS_DEF,STS,OS_STS,FRAULD_FLAG,USERREQUEST_FLAG,UNBILLING_FLAG,OS_STS_DTL) values ('1047','0','12','-1','-1','-1','7');
insert into SD.SYS_USER_STATUS_DTL(USER_STATUS_DEF,STS,OS_STS,FRAULD_FLAG,USERREQUEST_FLAG,UNBILLING_FLAG,OS_STS_DTL) values ('1048','0','11','-1','-1','-1','5');
insert into SD.SYS_USER_STATUS_DTL(USER_STATUS_DEF,STS,OS_STS,FRAULD_FLAG,USERREQUEST_FLAG,UNBILLING_FLAG,OS_STS_DTL) values ('1049','0','11','-1','-1','-1','7');
insert into SD.SYS_USER_STATUS_DTL(USER_STATUS_DEF,STS,OS_STS,FRAULD_FLAG,USERREQUEST_FLAG,UNBILLING_FLAG,OS_STS_DTL) values ('1050','0','12','-1','-1','-1','5');
insert into SD.SYS_USER_STATUS_DTL(USER_STATUS_DEF,STS,OS_STS,FRAULD_FLAG,USERREQUEST_FLAG,UNBILLING_FLAG,OS_STS_DTL) values ('1051','0','12','-1','-1','-1','7');
insert into SD.SYS_USER_STATUS_DTL(USER_STATUS_DEF,STS,OS_STS,FRAULD_FLAG,USERREQUEST_FLAG,UNBILLING_FLAG,OS_STS_DTL) values ('1052','0','12','-1','-1','-1','10');
insert into SD.SYS_USER_STATUS_DTL(USER_STATUS_DEF,STS,OS_STS,FRAULD_FLAG,USERREQUEST_FLAG,UNBILLING_FLAG,OS_STS_DTL) values ('1053','0','12','-1','-1','-1','11');
insert into SD.SYS_USER_STATUS_DTL(USER_STATUS_DEF,STS,OS_STS,FRAULD_FLAG,USERREQUEST_FLAG,UNBILLING_FLAG,OS_STS_DTL) values ('1054','0','12','-1','-1','-1','8');
insert into SD.SYS_USER_STATUS_DTL(USER_STATUS_DEF,STS,OS_STS,FRAULD_FLAG,USERREQUEST_FLAG,UNBILLING_FLAG,OS_STS_DTL) values ('1055','0','12','-1','-1','-1','40');
insert into SD.SYS_USER_STATUS_DTL(USER_STATUS_DEF,STS,OS_STS,FRAULD_FLAG,USERREQUEST_FLAG,UNBILLING_FLAG,OS_STS_DTL) values ('1056','0','12','-1','-1','-1','40');
insert into SD.SYS_USER_STATUS_DTL(USER_STATUS_DEF,STS,OS_STS,FRAULD_FLAG,USERREQUEST_FLAG,UNBILLING_FLAG,OS_STS_DTL) values ('1057','0','12','-1','-1','-1','20');
insert into SD.SYS_USER_STATUS_DTL(USER_STATUS_DEF,STS,OS_STS,FRAULD_FLAG,USERREQUEST_FLAG,UNBILLING_FLAG,OS_STS_DTL) values ('1058','0','12','-1','-1','-1','41');

insert into SD.SYS_USER_STATUS_AFFECT_DEF(USER_STATUS_DEF,USER_STATUS_NAME,DESCRIPTION,PRIORITY) values ('1000','开通            ','0','99');
insert into SD.SYS_USER_STATUS_AFFECT_DEF(USER_STATUS_DEF,USER_STATUS_NAME,DESCRIPTION,PRIORITY) values ('1001','申请停机        ','1','96');
insert into SD.SYS_USER_STATUS_AFFECT_DEF(USER_STATUS_DEF,USER_STATUS_NAME,DESCRIPTION,PRIORITY) values ('1002','挂失停机        ','2','92');
insert into SD.SYS_USER_STATUS_AFFECT_DEF(USER_STATUS_DEF,USER_STATUS_NAME,DESCRIPTION,PRIORITY) values ('1003','并机停机        ','3','91');
insert into SD.SYS_USER_STATUS_AFFECT_DEF(USER_STATUS_DEF,USER_STATUS_NAME,DESCRIPTION,PRIORITY) values ('1004','强制停机        ','4','90');
insert into SD.SYS_USER_STATUS_AFFECT_DEF(USER_STATUS_DEF,USER_STATUS_NAME,DESCRIPTION,PRIORITY) values ('1005','欠费停机        ','5','89');
insert into SD.SYS_USER_STATUS_AFFECT_DEF(USER_STATUS_DEF,USER_STATUS_NAME,DESCRIPTION,PRIORITY) values ('1006','申请销号        ','6','98');
insert into SD.SYS_USER_STATUS_AFFECT_DEF(USER_STATUS_DEF,USER_STATUS_NAME,DESCRIPTION,PRIORITY) values ('1007','高额停机        ','7','88');
insert into SD.SYS_USER_STATUS_AFFECT_DEF(USER_STATUS_DEF,USER_STATUS_NAME,DESCRIPTION,PRIORITY) values ('1008','欠费预销号      ','8','95');
insert into SD.SYS_USER_STATUS_AFFECT_DEF(USER_STATUS_DEF,USER_STATUS_NAME,DESCRIPTION,PRIORITY) values ('1009','欠费销号        ','9','97');
insert into SD.SYS_USER_STATUS_AFFECT_DEF(USER_STATUS_DEF,USER_STATUS_NAME,DESCRIPTION,PRIORITY) values ('1010','欠费半停机      ','A','87');
insert into SD.SYS_USER_STATUS_AFFECT_DEF(USER_STATUS_DEF,USER_STATUS_NAME,DESCRIPTION,PRIORITY) values ('1011','高额半停机      ','B','86');
insert into SD.SYS_USER_STATUS_AFFECT_DEF(USER_STATUS_DEF,USER_STATUS_NAME,DESCRIPTION,PRIORITY) values ('1012','正在欠费停机    ','C','85');
insert into SD.SYS_USER_STATUS_AFFECT_DEF(USER_STATUS_DEF,USER_STATUS_NAME,DESCRIPTION,PRIORITY) values ('1013','正在高额停机    ','D','84');
insert into SD.SYS_USER_STATUS_AFFECT_DEF(USER_STATUS_DEF,USER_STATUS_NAME,DESCRIPTION,PRIORITY) values ('1014','转网销号停机    ','E','93');
insert into SD.SYS_USER_STATUS_AFFECT_DEF(USER_STATUS_DEF,USER_STATUS_NAME,DESCRIPTION,PRIORITY) values ('1015','申请预销停机    ','F','94');
insert into SD.SYS_USER_STATUS_AFFECT_DEF(USER_STATUS_DEF,USER_STATUS_NAME,DESCRIPTION,PRIORITY) values ('1016','正在欠费预销号  ','H','81');
insert into SD.SYS_USER_STATUS_AFFECT_DEF(USER_STATUS_DEF,USER_STATUS_NAME,DESCRIPTION,PRIORITY) values ('1017','连带停机（帐户）','L','83');
insert into SD.SYS_USER_STATUS_AFFECT_DEF(USER_STATUS_DEF,USER_STATUS_NAME,DESCRIPTION,PRIORITY) values ('1018','连带停机（证件）','M','82');
insert into SD.SYS_USER_STATUS_AFFECT_DEF(USER_STATUS_DEF,USER_STATUS_NAME,DESCRIPTION,PRIORITY) values ('1019','骚扰电话特殊停机','R','80');
insert into SD.SYS_USER_STATUS_AFFECT_DEF(USER_STATUS_DEF,USER_STATUS_NAME,DESCRIPTION,PRIORITY) values ('1020','HLR加黑全停机   ','U','80');
insert into SD.SYS_USER_STATUS_AFFECT_DEF(USER_STATUS_DEF,USER_STATUS_NAME,DESCRIPTION,PRIORITY) values ('1021','申请销号        ','6','98');
insert into SD.SYS_USER_STATUS_AFFECT_DEF(USER_STATUS_DEF,USER_STATUS_NAME,DESCRIPTION,PRIORITY) values ('1022','申请销号        ','6','98');
insert into SD.SYS_USER_STATUS_AFFECT_DEF(USER_STATUS_DEF,USER_STATUS_NAME,DESCRIPTION,PRIORITY) values ('1023','开通            ','0','99');
insert into SD.SYS_USER_STATUS_AFFECT_DEF(USER_STATUS_DEF,USER_STATUS_NAME,DESCRIPTION,PRIORITY) values ('1024','申请停机        ','1','96');
insert into SD.SYS_USER_STATUS_AFFECT_DEF(USER_STATUS_DEF,USER_STATUS_NAME,DESCRIPTION,PRIORITY) values ('1025','挂失停机        ','2','92');
insert into SD.SYS_USER_STATUS_AFFECT_DEF(USER_STATUS_DEF,USER_STATUS_NAME,DESCRIPTION,PRIORITY) values ('1026','并机停机        ','3','91');
insert into SD.SYS_USER_STATUS_AFFECT_DEF(USER_STATUS_DEF,USER_STATUS_NAME,DESCRIPTION,PRIORITY) values ('1027','局方停机        ','4','90');
insert into SD.SYS_USER_STATUS_AFFECT_DEF(USER_STATUS_DEF,USER_STATUS_NAME,DESCRIPTION,PRIORITY) values ('1028','欠费停机        ','5','89');
insert into SD.SYS_USER_STATUS_AFFECT_DEF(USER_STATUS_DEF,USER_STATUS_NAME,DESCRIPTION,PRIORITY) values ('1029','高额停机        ','7','88');
insert into SD.SYS_USER_STATUS_AFFECT_DEF(USER_STATUS_DEF,USER_STATUS_NAME,DESCRIPTION,PRIORITY) values ('1030','欠费半停机      ','A','87');
insert into SD.SYS_USER_STATUS_AFFECT_DEF(USER_STATUS_DEF,USER_STATUS_NAME,DESCRIPTION,PRIORITY) values ('1031','高额半停机      ','B','86');
insert into SD.SYS_USER_STATUS_AFFECT_DEF(USER_STATUS_DEF,USER_STATUS_NAME,DESCRIPTION,PRIORITY) values ('1032','正在欠费停机    ','C','85');
insert into SD.SYS_USER_STATUS_AFFECT_DEF(USER_STATUS_DEF,USER_STATUS_NAME,DESCRIPTION,PRIORITY) values ('1033','正在高额停机    ','D','84');
insert into SD.SYS_USER_STATUS_AFFECT_DEF(USER_STATUS_DEF,USER_STATUS_NAME,DESCRIPTION,PRIORITY) values ('1034','转网销号停机    ','E','93');
insert into SD.SYS_USER_STATUS_AFFECT_DEF(USER_STATUS_DEF,USER_STATUS_NAME,DESCRIPTION,PRIORITY) values ('1035','申请预销停机    ','F','94');
insert into SD.SYS_USER_STATUS_AFFECT_DEF(USER_STATUS_DEF,USER_STATUS_NAME,DESCRIPTION,PRIORITY) values ('1036','正在欠费预销号  ','H','81');
insert into SD.SYS_USER_STATUS_AFFECT_DEF(USER_STATUS_DEF,USER_STATUS_NAME,DESCRIPTION,PRIORITY) values ('1037','连带停机（帐户）','L','83');
insert into SD.SYS_USER_STATUS_AFFECT_DEF(USER_STATUS_DEF,USER_STATUS_NAME,DESCRIPTION,PRIORITY) values ('1038','连带停机（证件）','M','82');
insert into SD.SYS_USER_STATUS_AFFECT_DEF(USER_STATUS_DEF,USER_STATUS_NAME,DESCRIPTION,PRIORITY) values ('1039','骚扰电话特殊停机','R','80');
insert into SD.SYS_USER_STATUS_AFFECT_DEF(USER_STATUS_DEF,USER_STATUS_NAME,DESCRIPTION,PRIORITY) values ('1040','HLR加黑全停机   ','U','80');
insert into SD.SYS_USER_STATUS_AFFECT_DEF(USER_STATUS_DEF,USER_STATUS_NAME,DESCRIPTION,PRIORITY) values ('1041','开通            ','0','99');
insert into SD.SYS_USER_STATUS_AFFECT_DEF(USER_STATUS_DEF,USER_STATUS_NAME,DESCRIPTION,PRIORITY) values ('1042','申请停机        ','1','96');
insert into SD.SYS_USER_STATUS_AFFECT_DEF(USER_STATUS_DEF,USER_STATUS_NAME,DESCRIPTION,PRIORITY) values ('1043','挂失停机        ','2','92');
insert into SD.SYS_USER_STATUS_AFFECT_DEF(USER_STATUS_DEF,USER_STATUS_NAME,DESCRIPTION,PRIORITY) values ('1044','并机停机        ','3','91');
insert into SD.SYS_USER_STATUS_AFFECT_DEF(USER_STATUS_DEF,USER_STATUS_NAME,DESCRIPTION,PRIORITY) values ('1045','局方停机        ','4','90');
insert into SD.SYS_USER_STATUS_AFFECT_DEF(USER_STATUS_DEF,USER_STATUS_NAME,DESCRIPTION,PRIORITY) values ('1046','欠费停机        ','5','89');
insert into SD.SYS_USER_STATUS_AFFECT_DEF(USER_STATUS_DEF,USER_STATUS_NAME,DESCRIPTION,PRIORITY) values ('1047','高额停机        ','7','88');
insert into SD.SYS_USER_STATUS_AFFECT_DEF(USER_STATUS_DEF,USER_STATUS_NAME,DESCRIPTION,PRIORITY) values ('1048','欠费半停机      ','A','87');
insert into SD.SYS_USER_STATUS_AFFECT_DEF(USER_STATUS_DEF,USER_STATUS_NAME,DESCRIPTION,PRIORITY) values ('1049','高额半停机      ','B','86');
insert into SD.SYS_USER_STATUS_AFFECT_DEF(USER_STATUS_DEF,USER_STATUS_NAME,DESCRIPTION,PRIORITY) values ('1050','正在欠费停机    ','C','85');
insert into SD.SYS_USER_STATUS_AFFECT_DEF(USER_STATUS_DEF,USER_STATUS_NAME,DESCRIPTION,PRIORITY) values ('1051','正在高额停机    ','D','84');
insert into SD.SYS_USER_STATUS_AFFECT_DEF(USER_STATUS_DEF,USER_STATUS_NAME,DESCRIPTION,PRIORITY) values ('1052','转网销号停机    ','E','93');
insert into SD.SYS_USER_STATUS_AFFECT_DEF(USER_STATUS_DEF,USER_STATUS_NAME,DESCRIPTION,PRIORITY) values ('1053','申请预销停机    ','F','94');
insert into SD.SYS_USER_STATUS_AFFECT_DEF(USER_STATUS_DEF,USER_STATUS_NAME,DESCRIPTION,PRIORITY) values ('1054','正在欠费预销号  ','H','81');
insert into SD.SYS_USER_STATUS_AFFECT_DEF(USER_STATUS_DEF,USER_STATUS_NAME,DESCRIPTION,PRIORITY) values ('1055','连带停机（帐户）','L','83');
insert into SD.SYS_USER_STATUS_AFFECT_DEF(USER_STATUS_DEF,USER_STATUS_NAME,DESCRIPTION,PRIORITY) values ('1056','连带停机（证件）','M','82');
insert into SD.SYS_USER_STATUS_AFFECT_DEF(USER_STATUS_DEF,USER_STATUS_NAME,DESCRIPTION,PRIORITY) values ('1057','骚扰电话特殊停机','R','80');
insert into SD.SYS_USER_STATUS_AFFECT_DEF(USER_STATUS_DEF,USER_STATUS_NAME,DESCRIPTION,PRIORITY) values ('1058','HLR加黑全停机   ','U','80');
COMMIT;
   
      EXCEPTION
      WHEN OTHERS THEN
           ROLLBACK;
           v_resulterrinfo:='P_ASP_INSERT_USERSTATUS err!:'||substr(SQLERRM,1,200);
           v_resultcode:='-1';
           RETURN;
    END;    
    COMMIT;
    
EXCEPTION
  WHEN OTHERS THEN
       v_resulterrinfo:=substr(SQLERRM,1,200);
       v_resultcode:='-1';
END;
/





